/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef nsHtml5LeanContentCreators_h
#define nsHtml5LeanContentCreators_h

// Generated parser tables name DOM factories even when a consumer only needs
// tree-builder state and speculative-load descriptors. In the lean build the
// creator values are never invoked, so erase the names before C++ lookup.
#  define NS_NewHTMLAnchorElement nullptr
#  define NS_NewHTMLAreaElement nullptr
#  define NS_NewHTMLAudioElement nullptr
#  define NS_NewHTMLBodyElement nullptr
#  define NS_NewHTMLBRElement nullptr
#  define NS_NewHTMLButtonElement nullptr
#  define NS_NewHTMLCanvasElement nullptr
#  define NS_NewHTMLDataElement nullptr
#  define NS_NewHTMLDataListElement nullptr
#  define NS_NewHTMLDetailsElement nullptr
#  define NS_NewHTMLDialogElement nullptr
#  define NS_NewHTMLDivElement nullptr
#  define NS_NewHTMLElement nullptr
#  define NS_NewHTMLEmbedElement nullptr
#  define NS_NewHTMLFieldSetElement nullptr
#  define NS_NewHTMLFontElement nullptr
#  define NS_NewHTMLFormElement nullptr
#  define NS_NewHTMLFrameElement nullptr
#  define NS_NewHTMLFrameSetElement nullptr
#  define NS_NewHTMLHeadingElement nullptr
#  define NS_NewHTMLHRElement nullptr
#  define NS_NewHTMLIFrameElement nullptr
#  define NS_NewHTMLImageElement nullptr
#  define NS_NewHTMLInputElement nullptr
#  define NS_NewHTMLLabelElement nullptr
#  define NS_NewHTMLLegendElement nullptr
#  define NS_NewHTMLLIElement nullptr
#  define NS_NewHTMLLinkElement nullptr
#  define NS_NewHTMLMapElement nullptr
#  define NS_NewHTMLMarqueeElement nullptr
#  define NS_NewHTMLMenuElement nullptr
#  define NS_NewHTMLMetaElement nullptr
#  define NS_NewHTMLMeterElement nullptr
#  define NS_NewHTMLModElement nullptr
#  define NS_NewHTMLObjectElement nullptr
#  define NS_NewHTMLOptGroupElement nullptr
#  define NS_NewHTMLOptionElement nullptr
#  define NS_NewHTMLOutputElement nullptr
#  define NS_NewHTMLParagraphElement nullptr
#  define NS_NewHTMLPictureElement nullptr
#  define NS_NewHTMLPreElement nullptr
#  define NS_NewHTMLProgressElement nullptr
#  define NS_NewHTMLScriptElement nullptr
#  define NS_NewHTMLSelectedContentElement nullptr
#  define NS_NewHTMLSelectElement nullptr
#  define NS_NewHTMLSharedElement nullptr
#  define NS_NewHTMLSharedListElement nullptr
#  define NS_NewHTMLSlotElement nullptr
#  define NS_NewHTMLSourceElement nullptr
#  define NS_NewHTMLSpanElement nullptr
#  define NS_NewHTMLStyleElement nullptr
#  define NS_NewHTMLSummaryElement nullptr
#  define NS_NewHTMLTableCaptionElement nullptr
#  define NS_NewHTMLTableCellElement nullptr
#  define NS_NewHTMLTableColElement nullptr
#  define NS_NewHTMLTableElement nullptr
#  define NS_NewHTMLTableRowElement nullptr
#  define NS_NewHTMLTableSectionElement nullptr
#  define NS_NewHTMLTemplateElement nullptr
#  define NS_NewHTMLTextAreaElement nullptr
#  define NS_NewHTMLTimeElement nullptr
#  define NS_NewHTMLTitleElement nullptr
#  define NS_NewHTMLTrackElement nullptr
#  define NS_NewHTMLUnknownElement nullptr
#  define NS_NewHTMLVideoElement nullptr
#  define NS_NewSVGAElement nullptr
#  define NS_NewSVGAnimateElement nullptr
#  define NS_NewSVGAnimateMotionElement nullptr
#  define NS_NewSVGAnimateTransformElement nullptr
#  define NS_NewSVGCircleElement nullptr
#  define NS_NewSVGClipPathElement nullptr
#  define NS_NewSVGDefsElement nullptr
#  define NS_NewSVGDescElement nullptr
#  define NS_NewSVGEllipseElement nullptr
#  define NS_NewSVGFEBlendElement nullptr
#  define NS_NewSVGFEColorMatrixElement nullptr
#  define NS_NewSVGFEComponentTransferElement nullptr
#  define NS_NewSVGFECompositeElement nullptr
#  define NS_NewSVGFEConvolveMatrixElement nullptr
#  define NS_NewSVGFEDiffuseLightingElement nullptr
#  define NS_NewSVGFEDisplacementMapElement nullptr
#  define NS_NewSVGFEDistantLightElement nullptr
#  define NS_NewSVGFEDropShadowElement nullptr
#  define NS_NewSVGFEFloodElement nullptr
#  define NS_NewSVGFEFuncAElement nullptr
#  define NS_NewSVGFEFuncBElement nullptr
#  define NS_NewSVGFEFuncGElement nullptr
#  define NS_NewSVGFEFuncRElement nullptr
#  define NS_NewSVGFEGaussianBlurElement nullptr
#  define NS_NewSVGFEImageElement nullptr
#  define NS_NewSVGFEMergeElement nullptr
#  define NS_NewSVGFEMergeNodeElement nullptr
#  define NS_NewSVGFEMorphologyElement nullptr
#  define NS_NewSVGFEOffsetElement nullptr
#  define NS_NewSVGFEPointLightElement nullptr
#  define NS_NewSVGFESpecularLightingElement nullptr
#  define NS_NewSVGFESpotLightElement nullptr
#  define NS_NewSVGFETileElement nullptr
#  define NS_NewSVGFETurbulenceElement nullptr
#  define NS_NewSVGFilterElement nullptr
#  define NS_NewSVGForeignObjectElement nullptr
#  define NS_NewSVGGElement nullptr
#  define NS_NewSVGImageElement nullptr
#  define NS_NewSVGLinearGradientElement nullptr
#  define NS_NewSVGLineElement nullptr
#  define NS_NewSVGMarkerElement nullptr
#  define NS_NewSVGMaskElement nullptr
#  define NS_NewSVGMetadataElement nullptr
#  define NS_NewSVGMPathElement nullptr
#  define NS_NewSVGPathElement nullptr
#  define NS_NewSVGPatternElement nullptr
#  define NS_NewSVGPolygonElement nullptr
#  define NS_NewSVGPolylineElement nullptr
#  define NS_NewSVGRadialGradientElement nullptr
#  define NS_NewSVGRectElement nullptr
#  define NS_NewSVGScriptElement nullptr
#  define NS_NewSVGSetElement nullptr
#  define NS_NewSVGStopElement nullptr
#  define NS_NewSVGStyleElement nullptr
#  define NS_NewSVGSVGElement nullptr
#  define NS_NewSVGSwitchElement nullptr
#  define NS_NewSVGSymbolElement nullptr
#  define NS_NewSVGTextElement nullptr
#  define NS_NewSVGTextPathElement nullptr
#  define NS_NewSVGTitleElement nullptr
#  define NS_NewSVGTSpanElement nullptr
#  define NS_NewSVGUnknownElement nullptr
#  define NS_NewSVGUseElement nullptr
#  define NS_NewSVGViewElement nullptr
#  define NS_NewCustomElement nullptr

#endif  // nsHtml5LeanContentCreators_h
