[package]
name = "icu4x_unicode_glue"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
description = "Small NaiveFox ICU4X Unicode property bridge"

[dependencies]
icu_casemap = { version = "~2.1.1", default-features = false, features = ["compiled_data"] }
icu_properties = { version = "~2.1.1", default-features = false, features = ["compiled_data"] }

[lib]
path = "src/lib.rs"
test = true
doctest = false
bench = false
doc = false
harness = true
